version: '3'

services:
  rss:
    build: .
    container_name: rss-feed
#    command: source venv/bin/activate && exec gunicorn -b :5000 --access-logfile - --error-logfile - rfeed:app
#    volumes:
#      - .:/home/rfeed
    ports:
      - "5000:5000"
